/*
 * Main.java
 *
 * Created on 31 maj 2007, 23:35
 */

package jebeno3d;

/**
 *
 * @author  arkadiusz
 */
public class Main extends javax.swing.JFrame {
  
  /** Creates new form Main */
  public Main() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
   // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
   private void initComponents() {
      jPanelWej = new javax.swing.JPanel();
      jLabelWej = new javax.swing.JLabel();
      jButtonWejWiz = new javax.swing.JButton();
      jButtonWejZap = new javax.swing.JButton();
      jPanel2 = new javax.swing.JPanel();
      jLabel2 = new javax.swing.JLabel();
      jButton2 = new javax.swing.JButton();
      jButton6 = new javax.swing.JButton();
      jPanel3 = new javax.swing.JPanel();
      jLabel3 = new javax.swing.JLabel();
      jButton3 = new javax.swing.JButton();
      jButton7 = new javax.swing.JButton();
      jPanel4 = new javax.swing.JPanel();
      jLabel4 = new javax.swing.JLabel();
      jButton4 = new javax.swing.JButton();
      jButton8 = new javax.swing.JButton();

      getContentPane().setLayout(new java.awt.GridLayout(0, 1, 1, 0));

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      jPanelWej.setBackground(new java.awt.Color(204, 255, 255));
      jLabelWej.setText("Modu\u0142 Wej\u015bciowy");

      jButtonWejWiz.setText("Wizualizacja");

      jButtonWejZap.setText("Zapisz");

      javax.swing.GroupLayout jPanelWejLayout = new javax.swing.GroupLayout(jPanelWej);
      jPanelWej.setLayout(jPanelWejLayout);
      jPanelWejLayout.setHorizontalGroup(
         jPanelWejLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jLabelWej, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWejLayout.createSequentialGroup()
            .addGap(164, 164, 164)
            .addComponent(jButtonWejZap)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButtonWejWiz))
      );
      jPanelWejLayout.setVerticalGroup(
         jPanelWejLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanelWejLayout.createSequentialGroup()
            .addComponent(jLabelWej)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
            .addGroup(jPanelWejLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jButtonWejWiz)
               .addComponent(jButtonWejZap)))
      );
      getContentPane().add(jPanelWej);

      jPanel2.setBackground(new java.awt.Color(255, 204, 204));
      jLabel2.setText("jLabel2");

      jButton2.setText("Wizualizacja");

      jButton6.setText("jButton6");

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addGap(164, 164, 164)
            .addComponent(jButton6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton2))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jButton2)
               .addComponent(jButton6)))
      );
      getContentPane().add(jPanel2);

      jPanel3.setBackground(new java.awt.Color(255, 255, 204));
      jLabel3.setText("jLabel3");

      jButton3.setText("Wizualizacja");

      jButton7.setText("jButton7");

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
            .addGap(164, 164, 164)
            .addComponent(jButton7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton3))
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jButton3)
               .addComponent(jButton7)))
      );
      getContentPane().add(jPanel3);

      jPanel4.setBackground(new java.awt.Color(204, 255, 204));
      jLabel4.setText("jLabel4");

      jButton4.setText("Wizualizacja");

      jButton8.setText("jButton8");

      javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
      jPanel4.setLayout(jPanel4Layout);
      jPanel4Layout.setHorizontalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
            .addGap(164, 164, 164)
            .addComponent(jButton8)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton4))
      );
      jPanel4Layout.setVerticalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel4Layout.createSequentialGroup()
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jButton4)
               .addComponent(jButton8)))
      );
      getContentPane().add(jPanel4);

      pack();
   }// </editor-fold>//GEN-END:initComponents
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Main().setVisible(true);
      }
    });
  }
  
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jButton3;
   private javax.swing.JButton jButton4;
   private javax.swing.JButton jButton6;
   private javax.swing.JButton jButton7;
   private javax.swing.JButton jButton8;
   private javax.swing.JButton jButtonWejWiz;
   private javax.swing.JButton jButtonWejZap;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabelWej;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JPanel jPanelWej;
   // End of variables declaration//GEN-END:variables
  
}
